dependencies:
  build:
    - node:10.15.1

build_targets:
  - name: default
    environment:
      - NODE_ENV=development
    commands:
      - npm install
      - npm run

ci:
  builds:
    - name: default
      build_target: default
